### ISSUE TITLE
Settings and Clipboard monitor windows only show in workspace 1

### ISSUE THREAD

**Issue by Perelandra0x309** [humdingerb/clipdinger#14]
If I summon "Settings..." or "Clipboard monitor..." from the App menu while not in Workspace 1 I either get brought to workspace 1 (I think if that window is already showing) or nothing happens but when I go to Workspace 1 the window is there.

**Comment by humdingerb** [comment]
You're right. I added the flag "B_ALL_WORKSPACES" for those windows, which is already used for the main window.

I don't think normal usage has those two windows opened very often, so I hope not too many people are annoyed by it. I'll wait with another point release a bit to see if more issues pop up...
Thanks, Brian!
