### ISSUE TITLE
Hide app in Deskbar

### ISSUE THREAD

**Issue by Perelandra0x309** [humdingerb/clipdinger#15]
I don't know if this is possible to do dynamically without changing the application flag to a background app.  But I use the deskbar fully expanded on the bottom of the screen and the Clipdinger app shows along with the other applications.  It would be nice if it is possible to have a setting to optionally hide it from the Deskbar apps list. see:
https://drive.google.com/file/d/0B8n9qMefrOQJTHdKUmxXQ3FFTjA/view?usp=sharing

**Comment by humdingerb** [comment]
Clipdinger is now a "Background app" (6963814ba6b639c93ebcbd0bac52ffea16ba03f8), So it's out of the Deskbar (aside the optional Replicant in the tray).
