### ISSUE TITLE
Deleting settings doesn't make the replicant colour to go back to default

### ISSUE THREAD

**Issue by ojasva** [humdingerb/clipdinger#19]
I deleted the settings files from .../settings/clipdinger however still the replicant doesn't go back to default colour as settings

**Comment by humdingerb** [comment]
Care to elaborate? I don't quite understand what this ticket is about...

**Comment by humdingerb** [comment]
Ah, I now understand.
The Clipboard Monitor's colour isn't saved explicitly. It's a replicant that gets un/archived with its host application (Tracker).

I don't consider going back to the default grey is a particularly useful feature.
