### ISSUE TITLE
Editing Title for content in Replicant doesn't change the text in Replicant

### ISSUE THREAD

**Issue by ojasva** [humdingerb/clipdinger#22]
Drag and drop something in Replicant, open Clipdinger and edit the title of that text. It should change the same in Replicant. However, it doesn't.

**Comment by humdingerb** [comment]
The replicant is independent of Clipdinger. It just shows what's inside the clipboard.
I think it makes sense not to check if some clip is a favourite and show its title instead. This way it's consistently showing the clipboard contents and you wouldn't wonder why you copied some text and another is displayed.
