### ISSUE TITLE
Removing the first item from the list on the main window crashes Clipdinger

### ISSUE THREAD

**Issue by nx6-archived** [humdingerb/clipdinger#30]
In the left-hand side list with two or more items, removing the first one immediately crashes Clipdinger.
When there is just one item, deleting it does nothing. Clipdinger does not crash but the item remains.
Please find a debug report and let me know if you need anyting else.
[Clipdinger-14340-debug-20-09-2023-13-27-57.report.txt](https://github.com/humdingerb/clipdinger/files/12673632/Clipdinger-14340-debug-20-09-2023-13-27-57.report.txt)

**Comment by nexus6-haiku** [comment]
I'm too lazy to read the docs! I see your point but I'd recommend to add an alert, at least.

**Comment by humdingerb** [comment]
Thinking about it more, it's more consistent to have users be able to delete the current clipboard contents as well, if they want. More of the reasoning in the commit message of f6412c8cd4fd777e15ec6c7e84dc983b5fc257e4.

**Comment by nexus6-haiku** [comment]
I agree with the reasoning except that "clear clip history" might be misleading.
If you clear the history in a browser, you clear also the latest page visited.
I think this is what a user expects from that command.
I suggest using a different term ("previous/past items"?) or differentiating the current item from the "history" (you remember ClipUp, don't you?).

**Comment by humdingerb** [comment]
> I agree with the reasoning except that "clear clip history" might be misleading.
If you clear the history in a browser, you clear also the latest page visited.

But in this case, it would be like also clearing the currently open webpage.
I don't think that users expect to lose the current clipboard contents when they choose to  clear the "history" == "past items".
I don't think too many people have an issue with the current behaviour. In fact, I doubt the "Clear clip history" is a menu item invoked often... :)

I don't plan to break out the current clipboard item from the history list. I like the compact layout. ClipUp was the initial inspiration for Clipdinger, but I have to admit I don't remember much of its details.
