### ISSUE TITLE
Uninstalling Clipdinger does not stop the device add-on

### ISSUE THREAD

**Issue by lonemadmax** [humdingerb/clipdinger#32]
Ref [trac #19100](https://dev.haiku-os.org/ticket/19100)

[ClipdingerInputDevice::Stop](https://github.com/humdingerb/clipdinger/blob/5906360fc75bbe9621fc3b5c99f55857d98c0ef1/input_device/InputDevice.cpp#L90) waits for the listener thread to finish, but that is always [looping on a port read](https://github.com/humdingerb/clipdinger/blob/5906360fc75bbe9621fc3b5c99f55857d98c0ef1/input_device/InputDevice.cpp#L120) until an error occurs, so it will continue until the port is deleted.

If there's no problem with the listener stopping with unread messages one solution may be to delete the port before waiting for the thread; that should unblock the port read and exit the loop.

Another possible solution would be something like [KeyCursor's](https://github.com/HaikuArchives/KeyCursor/blob/master/src/KeyCursorDevice.cpp) sending of a quit message with a semaphore and waiting for that to be processed.

**Comment by humdingerb** [comment]
Thanks @lonemadmax!
I'm still not quite sure what has changed in Haiku that resulted in this stuck-in-a-loop, though. Clipdinger's InputDevice is pretty much unchanged from when I "borrowed" it from ClipUp about a decade ago, and it never produced the freezing on update...

In any case, it seems to work nicely with 9f5c7c7d569f7fcd8323638190d6ad522ff6fbee.
Thanks!

**Comment by lonemadmax** [comment]
It probably has been there all the time. Until my changes to the mouse settings stuff it would go unnoticed, with no freezing or sluggishness. And it's not a busy loop, so you wouldn't even see a pegged core.
