### ISSUE TITLE
Don't force to minimize after clicking paste to sprunge

### ISSUE THREAD

**Issue by raefaldhia** [humdingerb/clipdinger#9]
The window force to minimize after clicking `paste to sprunge`.

**Comment by humdingerb** [comment]
Why not? Keeping it open slows the work flow. If it didn't work, you'll see it when psting and you paste the error message instead. Or use the clipbord monitor if you need to see the URL before pasting.

**Comment by raefaldhia** [comment]
Yeah sometimes i want to see the link and paste some clipboard to sprunge (not only once) or it would be good to add option whether we'll disable it or not inside the settings just like the `auto-paste`.

**Comment by humdingerb** [comment]
Hmm, you may have a point. While a user can always use drag&drop to paste several clips into an application, that doesn't work with sprunging, of course.
OTOH, I suppose it's much more common to sprunge only one clip. That it would be annoying to have  the window stay open. And having to keep re-setting the preferences is even worse.

As it would probably be a seldomly used feature, a possible solution would be to make it a "hidden" power user feature that's explained in the help file: Holding SHIFT while sprunging keeps the window open.
I'll think about it some more, probably for a post-1.0 release.
Thanks!

**Comment by humdingerb** [comment]
Implementation was easy enough. Done with 79d2ffa.
